### PR TITLE
Added a few meta tags

### PR DESCRIPTION
**Pull request by cquanu**
Disable zoom in Bus Arrivals page.
Added icon for Bus Arrivals page.
Added Apple Web App Meta tags

busrouterfull

Visit https://rawgit.com/cquanu/busrouter-sg/master/index.html. Add to Home Screen

### CODE REVIEW

**Comment by cheeaun** [comment]
Few issues:

- I added the web app on home screen, click to a bus stop, click 'Show bus arrival times here', it pops the arrival page *inside* the "app" and can't **go back**.
- I'm not sure if anyone would actually add the Bus Arrival page on the home screen, since it doesn't have a *landing* page by itself (yet).
- Even when Bus Arrival page can be added, it probably shouldn't have the same icon as Bus Router itself? 💭

**Comment by cquanu** [comment]
Yes you're right. How about adding a "back to home" link at the bottom of the arrival page?

back

I'm seeing this on my home screen

image1

It's hard to tell that is BusRouter SG because it doesn't have a proper icon.

**Comment by cquanu** [comment]
I guess some people will "bookmark" add to home screen their bus arrival page to their home screen. So they get to their bus arrival timings quickly.

**Comment by cheeaun** [comment]
Closing this PR now that I've rebuilt everything. In brief, the site is now PWA-ed, except for the bus arrivals page.

**Pull request closed without merging**
